import os
import sys
import json

import streamlit as st

# Placeholder function to query Qwen model (replace with real API)
def ask_qwen(question: str) -> str:
    """Send a question to the Qwen LLM and return the answer.

    Currently this is a stub that echoes the question. Replace with actual
    API call using Ollama, OpenAI, OpenRouter, etc.
    """
    # Example stub implementation – echo the question
    return f"Answer (stub): {question}"

# CSS styling – blue themed version of the provided CSS
CUSTOM_CSS = """
/* Base colors */
:root {
    --border: #e0e0e0;
    --text: #0d47a1;           /* deep blue */
    --text-dim: #1565c0;       /* lighter blue */
    --text-muted: #42a5f5;    /* accent blue */
    --red: #d32f2f;            /* keep error red */
    --err: #c62828;
    --card: #e3f2fd;           /* very light blue background */
}

/* ---- inline approval (in a chat ledger entry) --------------------------- */
.apc {
  margin: 10px 0;
  max-width: 560px;
}
.apc-head {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  font-family: var(--mono, monospace);
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 1.4px;
  color: var(--text-dim);
  padding-bottom: 6px;
  border-bottom: 1px solid var(--border);
}
.apc-label.hot { color: var(--red); }
.apc-id { letter-spacing: 0.4px; text-transform: none; }
.apc-call { border-bottom: 1px solid var(--border); }
.apc-call-head {
  display: flex;
  align-items: baseline;
  gap: 12px;
  width: 100%;
  padding: 9px 2px;
  background: none;
  border: none;
  text-align: left;
  color: var(--text);
}
.apc-call-head:hover .apc-caret { color: var(--text-muted); }
.apc-call-head.as-text { cursor: default; }
.apc-tool { font-size: 12px; color: var(--text); white-space: nowrap; }
.apc-args { flex: 1; min-width: 0; font-size: 11px; color: var(--text-dim); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.apc-caret { font-size: 10px; color: var(--text-dim); }
.apc-call-body { padding: 0 2px 10px; }
.apc-kv { display: flex; gap: 12px; align-items: baseline; padding: 2px 0; }
.apc-k { font-size: 10.5px; color: var(--text-dim); min-width: 72px; }
.apc-v { font-size: 11px; color: var(--text-muted); word-break: break-word; white-space: pre-wrap; }
.apc-actions { display: flex; align-items: center; gap: 8px; padding: 10px 2px 2px; }
.apc-note { font-size: 11px; color: var(--text-dim); padding: 8px 2px 2px; }
.apc-note.err { color: var(--err); }

/* ---- artifact ledger (under an answer) ----------------------------------- */
.afc { margin: 10px 0 2px; max-width: 560px; }
.afc-head { font-family: var(--mono, monospace); font-size: 10px; text-transform: uppercase; letter-spacing: 1.4px; color: var(--text-dim); padding-bottom: 6px; border-bottom: 1px solid var(--border); }
.afc-row { display: flex; align-items: baseline; gap: 12px; padding: 9px 2px; border-bottom: 1px solid var(--border); font-size: 13px; }
.afc-row:hover { background: var(--card); }
.afc-name { white-space: nowrap; }
.afc-meta { flex: 1; min-width: 0; font-size: 10.5px; color: var(--text-dim); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.afc-get { background: none; border: none; padding: 0; font-size: 10.5px; letter-spacing: 0.6px; color: var(--text-dim); cursor: pointer; }
.afc-get:hover { color: var(--text); }
.afc-get:disabled { cursor: default; opacity: 0.6; }
.afc-get.err, .afc-state.err { color: var(--err); }
.afc-state { font-size: 10.5px; letter-spacing: 0.6px; }
"""

st.set_page_config(page_title="Qwen Terminal Chat", layout="centered")
st.markdown(f"<style>{CUSTOM_CSS}</style>", unsafe_allow_html=True)

st.title("💬 Qwen Knowledge‑Base Terminal")
st.write("Ask a question about the NEPSE system or any other topic. The answer is generated by the Qwen model (stub implementation).")

question = st.text_input("Your question:", "")
if st.button("Send") and question.strip():
    with st.spinner("Thinking…"):
        answer = ask_qwen(question.strip())
    # Render answer in a styled block
    st.markdown(f"""
    <div class=\"apc\">
      <div class=\"apc-head\"><span>Question</span></div>
      <div class=\"apc-call-head as-text\">{question}</div>
      <div class=\"apc-head\"><span>Answer</span></div>
      <div class=\"apc-call-body\">{answer}</div>
    </div>
    """, unsafe_allow_html=True)
